name: Tests
concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run style/security checks & tests
    container:
      image: node:22-slim
    steps:
      - uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'yarn'
      - run: |
          yarn -v
          yarn

      - name: Lint
        run: yarn run lint

      - name: Audit Prod Dependencies
        run: yarn audit --groups dependencies || true

      - name: Build
        run: yarn run build

      - name: Test
        run: yarn run test
